### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by mbr** [aphor/datasize#9]
Sorry to bring this up but: The PyPI page lists the license as GPL3, while the LICENSE.txt file is LGPL3. Could you correct one or the other?

**Comment by aphor** [comment]
It should be LGPL3. Thanks for noticing. I'll update the PyPi metadata.

**Comment by aphor** [comment]
It should be LGPL3. Thanks for noticing. I'll update the PyPi metadata.

**Comment by aphor** [comment]
License: LGPL3
